<?
$PERM["bitrix"]["9"]="D";
$PERM["service"]["*"]="X";
$PERM["seller"]["7"]="X";
$PERM["seller"]["9"]="X";
$PERM["seller"]["*"]="D";
$PERM["login"]["9"]="X";
$PERM["buyer"]["6"]="X";
$PERM["buyer"]["9"]="X";
$PERM["buyer"]["*"]="D";
$PERM["ads"]["9"]="X";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>